name: Build

on: [push]

jobs:
  HUGO_BUILD:
    name: Build website with Hugo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16', '20' ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.52'
      - name: Install jsonschema
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Install JS dependencies
        working-directory: ./themes/coopcycle
        run: |
          npm ci
          npm run build
          npm prune
      - name: Build
        run: hugo
      - name: Validate JSON schema
        run: jsonschema --instance public/coopcycle.json coopcycle.schema
